version: '2'
services:
    speedtest-db:
        build: "./database"
        restart: always
        volumes:
            - /data/speedtest:/var/lib/postgresql/data
        env_file:
            - ./db.env
        ports:
            - "5432:5432"

    speedtest:
        build: "./speedtest"
        restart: always
        depends_on: 
            - speedtest-db
        env_file:
            - ./db.env
        environment:
            POSTGRES_HOST: "speedtest-db"
            POSTGRES_PORT: "5432"
    
    speedtest-api:
        build: "./webapi"
        restart: always
        depends_on:
            - speedtest-db
        env_file:
            - ./db.env
        environment:
            POSTGRES_HOST: "speedtest-db"
            POSTGRES_PORT: "5432"
        ports:
            - "7000:7000"

    speedtest-app:
        build: "./webapp"
        restart: always
        ports: 
            - "80:80"
        depends_on: 
            - speedtest-api