version: '2'
services:
    speedtest-db:
        build: "./database"
        restart: always
        volumes:
            - /data/speedtest:/var/lib/postgresql/data
        env_file:
            - ./db.env
        ports:
            - "5432:5432"

    speedtest:
        build: "./speedtest"
        restart: always
        depends_on: 
            - speedtest-db
        env_file:
            - ./db.env
        environment:
            POSTGRES_HOST: "speedtest-db"
            POSTGRES_PORT: "5432"
    
    speedtest-api:
        build: "./webapi"
        restart: always
        depends_on:
            - speedtest-db
        env_file:
            - ./db.env
        environment:
            POSTGRES_HOST: "speedtest-db"
            POSTGRES_PORT: "5432"
        ports:
            - "7000:7000"

    speedtest-app:
        build: "./webapp"
        restart: always
        ports: 
            - "80:80"
        environment:
            API_HOST: "192.168.0.185" # Optional, defaults to the 'hostname' of the webapp e.g. '192.168.1.69', or 'speedtest.domain.com'
            API_PORT: "7000" # Optional, only needed if you change the above 'speedtest-api' port
            API_PROTOCOL: "http" # Optional, defaults to the http/https protocol used to access the webapp
        depends_on: 
            - speedtest-api