version: '2'
serivces:
    speedtest-db:
        #image: "postgres:12.3-alpine"
        build: "./database"
        restart: always
        volumes:
            - /data/speedtest:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: pwd

    speedtest:
        build: "./speedtest"
        #image: speedtest:latest
        #environment:
        depends_on: 
            - speedtest-db
    
    speedtest-api:
        build: "./webapi"
        depends_on:
            - speedtest-db

    speedtest-app:
        build: "./webapp"
        #image: speedtest-app:latest
        ports: 
            - "8000:80"
        depends_on: 
            - speedtest-api
networks:
    public:
        external: true