FROM python:3.7-alpine

WORKDIR /app

RUN apk update && \
    apk add --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev

RUN pip3 install speedtest-cli fire psycopg2

COPY ./speedtester.py ./

# Create entry point
CMD [ "sh", "-c", "python -u speedtester.py --pwd=\"$POSTGRES_PASSWORD\" --host=\"$POSTGRES_HOST\" --port=\"$POSTGRES_PORT\"" ]
