FROM node:12.18.0-alpine

WORKDIR /app
ENV PATH /app/node_modules.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

EXPOSE 8000

# start app
CMD ["npm", "start"]