FROM node:12.18.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

RUN npm run build

# production environment
FROM nginx:stable-alpine
RUN apk add --no-cache gettext
COPY ./app/env.template.js /usr/share/nginx/html
COPY nginx-entrypoint.sh /
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "sh", "/nginx-entrypoint.sh" ]